-- Base de dades Tienda
SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio*1.1 FROM producto;
SELECT nombre AS "nom de producto", precio AS "euros", precio*1.1 AS "dolars" FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(LEFT(nombre, 2)) FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio, 0) FROM producto;
SELECT fabricante.codigo FROM fabricante INNER JOIN producto ON fabricante.codigo=producto.codigo_fabricante;
SELECT DISTINCT fabricante.codigo FROM fabricante INNER JOIN producto ON fabricante.codigo=producto.codigo_fabricante;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3, 2 ;
SELECT nombre,precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre,precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante="2";
SELECT producto.nombre,precio,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo;
SELECT producto.nombre,precio,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo ORDER BY fabricante.nombre;
SELECT producto.codigo,producto.nombre,producto.codigo_fabricante,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo;
SELECT producto.nombre,MIN(precio),fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo;
SELECT producto.nombre,MAX(precio),fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo;
SELECT producto.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE fabricante.nombre="Lenovo";
SELECT producto.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE (fabricante.nombre="Crucial") AND (precio>200);
SELECT producto.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE (fabricante.nombre="Asus") OR (fabricante.nombre="Hewlett-Packard") OR (fabricante.nombre="Seagate");
SELECT producto.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE fabricante.nombre IN ("Asus", "Hewlett-Packard", "Seagate");
SELECT producto.nombre,precio FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE fabricante.nombre LIKE "%e";
SELECT producto.nombre,precio FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE fabricante.nombre LIKE "%w%";
SELECT producto.nombre,precio,fabricante.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE precio>=180 ORDER BY precio DESC, producto.nombre ASC;
SELECT DISTINCT fabricante.nombre,fabricante.codigo FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo; 
SELECT fabricante.nombre,producto.nombre FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante=fabricante.codigo;
SELECT fabricante.nombre,producto.nombre FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante=fabricante.codigo WHERE producto.codigo_fabricante IS NULL;
SELECT producto.nombre FROM producto, fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND fabricante.nombre="Lenovo";
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto,fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND (fabricante.nombre="Lenovo") );
SELECT producto.nombre FROM producto,fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND fabricante.nombre="Lenovo" AND precio=(SELECT MAX(precio) FROM producto,fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND (fabricante.nombre="Lenovo") );
SELECT producto.nombre FROM producto,fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND fabricante.nombre="Hewlett-Packard" AND precio=(SELECT MIN(precio) FROM producto,fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND (fabricante.nombre="Hewlett-Packard") );
SELECT producto.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE precio>=(SELECT MAX(precio) FROM producto,fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND (fabricante.nombre="Lenovo") );
SELECT producto.nombre FROM producto INNER JOIN fabricante ON producto.codigo_fabricante=fabricante.codigo WHERE (fabricante.nombre="Asus") AND precio>(SELECT AVG(precio) FROM producto,fabricante WHERE producto.codigo_fabricante=fabricante.codigo AND (fabricante.nombre="Asus") );
-- Base de dades Universidad
-- Exercici 1
SELECT apellido1, apellido2, nombre FROM  persona WHERE tipo="alumno" ORDER BY apellido1, apellido2, nombre;
SELECT  apellido1, apellido2, nombre FROM  persona WHERE (tipo="alumno") AND (telefono IS null);
SELECT  apellido1, apellido2, nombre FROM  persona WHERE (tipo="alumno") AND (fecha_nacimiento BETWEEN "1999-01-01" AND "1999-12-31");
SELECT  apellido1, apellido2, nombre FROM  persona WHERE (tipo="profesor") AND (telefono IS null) AND (nif LIKE "%K");
SELECT nombre FROM asignatura WHERE cuatrimestre=1 AND curso=3 AND id_grado=7;
SELECT  apellido1, apellido2, persona.nombre, departamento.nombre FROM  persona,profesor,departamento WHERE (tipo="profesor") AND id_profesor=persona.id AND departamento.id=id_departamento ORDER BY apellido1, apellido2, persona.nombre;
SELECT asignatura.nombre, anyo_inicio, anyo_fin FROM asignatura, curso_escolar, persona, alumno_se_matricula_asignatura WHERE persona.id=alumno_se_matricula_asignatura.id_alumno AND alumno_se_matricula_asignatura.id_asignatura=asignatura.id AND alumno_se_matricula_asignatura.id_curso_escolar=curso_escolar.id AND persona.nif="26902806M";
SELECT DISTINCT departamento.nombre FROM departamento,profesor,asignatura,grado WHERE departamento.id=profesor.id_departamento AND profesor.id_profesor=asignatura.id_profesor AND grado.id=asignatura.id_grado AND grado.nombre="Grado en Ingeniería Informática (Plan 2015)";
SELECT DISTINCT persona.apellido1, persona.apellido2, persona.nombre FROM persona,curso_escolar,alumno_se_matricula_asignatura WHERE alumno_se_matricula_asignatura.id_alumno=persona.id AND alumno_se_matricula_asignatura.id_curso_escolar=curso_escolar.id AND curso_escolar.anyo_inicio=2018 AND curso_escolar.anyo_fin=2019;
-- Exercici 2 LEFT JOIN i RIGHT JOIN
SELECT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM persona LEFT JOIN profesor ON persona.id=profesor.id_profesor LEFT JOIN departamento ON profesor.id_departamento=departamento.id  WHERE persona.tipo="profesor" ORDER BY departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre;
SELECT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM persona LEFT JOIN profesor ON persona.id=profesor.id_profesor LEFT JOIN departamento ON profesor.id_departamento=departamento.id  WHERE persona.tipo="profesor" AND departamento.id IS NULL ORDER BY departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre;
SELECT departamento.nombre FROM departamento LEFT JOIN profesor ON departamento.id=profesor.id_departamento WHERE profesor.id_departamento IS NULL ORDER BY departamento.nombre;
SELECT asignatura.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM persona JOIN profesor ON persona.id=profesor.id_profesor LEFT JOIN asignatura ON profesor.id_profesor=asignatura.id_profesor WHERE asignatura.id_profesor IS NULL ORDER BY asignatura.nombre, persona.apellido1, persona.apellido2, persona.nombre;
SELECT asignatura.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM persona JOIN profesor ON persona.id=profesor.id_profesor RIGHT JOIN asignatura ON profesor.id_profesor=asignatura.id_profesor WHERE asignatura.id_profesor IS NULL ORDER BY asignatura.nombre, persona.apellido1, persona.apellido2, persona.nombre;
SELECT departamento.nombre FROM departamento LEFT JOIN profesor ON departamento.id=profesor.id_departamento  LEFT JOIN asignatura ON profesor.id_profesor=asignatura.id_profesor LEFT JOIN alumno_se_matricula_asignatura ON asignatura.id=alumno_se_matricula_asignatura.id_asignatura GROUP BY departamento.nombre HAVING COUNT(alumno_se_matricula_asignatura.id_curso_escolar)=0  ;
-- Exercici 3 Consultes resum
SELECT COUNT(id) FROM persona WHERE persona.tipo="alumno";
SELECT COUNT(id) FROM persona WHERE persona.tipo="alumno" AND (fecha_nacimiento BETWEEN "1999-01-01" AND "1999-12-31");
SELECT departamento.nombre, COUNT(profesor.id_departamento) FROM profesor JOIN departamento ON departamento.id=profesor.id_departamento GROUP BY profesor.id_departamento ORDER BY COUNT(profesor.id_departamento) DESC;
SELECT departamento.nombre, COUNT(profesor.id_departamento) FROM profesor RIGHT JOIN departamento ON profesor.id_departamento=departamento.id GROUP BY departamento.id ORDER BY COUNT(profesor.id_departamento) DESC;
SELECT grado.nombre, COUNT(asignatura.id_grado) FROM grado 	LEFT JOIN asignatura ON grado.id=asignatura.id_grado GROUP BY grado.id ORDER BY COUNT(asignatura.id_grado) DESC;
SELECT grado.nombre, COUNT(asignatura.id_grado) FROM grado JOIN asignatura ON grado.id=asignatura.id_grado GROUP BY grado.id  HAVING COUNT(asignatura.id_grado)>40  ORDER BY COUNT(asignatura.id_grado) DESC ;
SELECT grado.nombre, asignatura.tipo, SUM(asignatura.creditos) FROM grado JOIN asignatura ON grado.id=asignatura.id_grado GROUP BY grado.nombre, asignatura.tipo;
SELECT anyo_inicio, COUNT(alumno_se_matricula_asignatura.id_curso_escolar) FROM alumno_se_matricula_asignatura LEFT JOIN curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar=curso_escolar.id GROUP BY id_curso_escolar;
SELECT profesor.id_profesor, persona.nombre, persona.apellido1, persona.apellido2, COUNT(asignatura.id_profesor) FROM profesor JOIN persona ON persona.id=profesor.id_profesor LEFT JOIN asignatura ON profesor.id_profesor=asignatura.id_profesor GROUP BY profesor.id_profesor ORDER BY COUNT(asignatura.id_profesor) DESC;
SELECT * FROM persona WHERE persona.tipo="alumno" AND persona.fecha_nacimiento=(SELECT MAX(persona.fecha_nacimiento) FROM persona)  ;
SELECT departamento.nombre,persona.nombre, persona.apellido1, persona.apellido2 FROM persona JOIN profesor ON persona.id=profesor.id_profesor JOIN departamento ON profesor.id_departamento=departamento.id LEFT JOIN asignatura ON profesor.id_profesor=asignatura.id_profesor WHERE asignatura.id_profesor IS null;